### ISSUE TITLE
help with rotations on custom avatar 

### ISSUE THREAD

**Issue by ireneb612** [TemugeB/python_stereo_camera_calibrate#1] opened 2022-07-14 14:33 UTC
Hi! A big thank for your work, very nice and helpful!

I'm trying to move my custom avatar with some generated keypoints!
What I first did was to take your raw data and sen it to my avatar to see what it is doing!
Here you can see the first frame of the avatar moving only the left shoulder
![Cattura](https://user-images.githubusercontent.com/69512318/179007419-b92db4c3-bbf2-4790-9a9a-d68523bbc56d.PNG)

So it is kind of strange! 
I know it was a fast try, but may you help to understand where I have to change your code? 
Is it due to the Rotation?

The avatar is on the Threejs coordinate system !

Thank you

**Comment by TemugeB** [comment] 2022-07-15 01:50
Hi. Thanks for checking out my package. But this is the camera calibration package. I'm not sure exactly what you did. Could you provide more details? There is quite a lot that can go wrong with sending pose data that only accepts a specific format.

**Comment by ireneb612** [comment] 2022-07-15 08:45
@TemugeB  Yes I meant posting this on your  **joint_angles_calculate** repository! I took your data **kpts_3d.dat** and calculated the euler rotations and then tranformed them to quaternion with this function : 
[https://automaticaddison.com/how-to-convert-euler-angles-to-quaternions-using-python/](url)

I tried both your implementation of the Decompose_ZYX and Decompose ZXY functions but in both cases the arms are moving back like this:
![Cattura](https://user-images.githubusercontent.com/69512318/179187975-af755375-ab1e-4618-b831-d4cbf9f2b691.PNG)

**Comment by TemugeB** [comment] 2022-07-16 00:58
I think kpts_3d contain pose key points in Cartesian coordinates and not joint angles. Is your avatar expecting joint angles?

I would suggest you put in the joint angles one by one to ensure that it is forming the pose in the way that you think it is supposed to work. Also make sure that the joint angles are going in in the correct units, radians or degrees.

**Comment by ireneb612** [comment] 2022-07-16 18:55
@TemugeB i took your coordinates and ran your code to get the Euler rotations! 
Then I used a function to go from Euler to quaternion rotation and this is the result.

**Comment by TemugeB** [comment] 2022-07-18 06:02
I see. Still, try to input some known rotations to make sure the pose output is what you expect. For example, rotate the root position by some angle and see if the avatar also rotates the way you expect it. Also try the same with joints further away from the root. I'm not sure if the problem is on my side of the code or on your side. But some debugging might get you some answers.

**Comment by ireneb612** [comment] 2022-07-18 09:18
@TemugeB  Ok thank you!

**Comment by ireneb612** [comment] 2022-07-18 09:52
@TemugeB  do you output the euler rotation in degree or radiants?

**Comment by TemugeB** [comment] 2022-08-05 03:12
I'm closing this issue since no new comment was added.

**Closed as completed by TemugeB** 2022-08-05 03:12 UTC
